server:
  port: 8082
spring:
  message:
    web-hook-list: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=b4a30fc5-7963-42d3-87f4-9905c8e17584
logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: webchat
      address:
      ip: 192.168.2.138
      port: 8081
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
# 节假日 appcode 为密钥 链接每天可以调用100 超过收费
holiday:
  url: https://api.topthink.com/calendar/month
  appcode: 614d91184cbda3282c6810b29856b4ec
